### ISSUE TITLE
Pangaea | Transactions with the same ID number (pairs)

### ISSUE THREAD

**Issue by BrunoMarshall** [harmony-one/pangaea-community#76]
Transactions appears double or/with  same ID number
How to recreate this issue:

- Run 1000 TX:

for n in {1..1000}; do ./wallet.sh -t transfer --from one1kkznllwcpcqakvmpqrll5yzp9tdjnf4ufnxcl6 --to one1nqkv7j2tzvqfu684cxdtudvx3k6nmgfml5wng2 --amount 0.01 --pass pass: ; done ;

after some hours the output will be this:
![image](https://user-images.githubusercontent.com/35432495/65836495-5bffd780-e2f1-11e9-9e34-2b42a61f4a2e.png)

I will perform more test to check:

- If effectively there are 2 TX with changing balance
- if only one is succeed and the other rejected

**Comment by SebastianJ** [comment]
The tx id you receive when sending via the wallet is the id of an attempted transfer.

If you submit an identical transfer (in terms of the receiving address and the amount) before your previous tx has been included in a block (i.e. it is pending) you'll just get the same tx id because the previous transaction is still waiting to be included. The pending queue is essentially filtering out transactions with duplicate data before including them in a block.

Randomize the amount sent or randomize attached base64 data for every transaction and you should get a unique tx id every time.

**Comment by BrunoMarshall** [comment]
I can´t check currently on the explorer, because is not working properly.
